name: Generate GitHub Snake Contribution Graph

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *" # Daily

jobs:
  generate:
    name: Generate and Push Snake Contribution Graph
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate files
        # Faster action to only generate SVG files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg?color_snake=#F42A41&color_dots=#EBEDF0,#9BE9A8,#40C463,#30A14E,#216E39
            dist/github-snake-dark.svg?color_snake=#F42A41&color_dots=#161B22,#0E4429,#006D32,#26A641,#39D353

      - name: Push files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: snake-graph-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
