name: Generate GitHub Snake Contribution Graph

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *" # Daily

jobs:
  generate:
    name: Generate and Push Snake Contribution Graph
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate files
        # Faster action to only generate SVG files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-light.svg?color_snake=##C38F8F&color_dots=#cabff6,#af8dff,#9964f4,#984bf1,#763cd9
            dist/github-snake-dark.svg?color_snake=##C38F8F&color_dots=#cabff6,#af8dff,#9964f4,#984bf1,#763cd9

      - name: Push files to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-snk-contribs-graph-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
